name: generate docs
on: 
  [push]
permissions:
  contents: read
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Generate docs
      uses: Microsoft/ps-docs@333fc57dfef2479e0c6457600bb4c7a1316783ba # main as of 2021-08-05
